FROM node:13

ARG SERVICE
ENV SERVICE="$SERVICE"

RUN echo "Building DEV env for ${SERVICE}."

# Setting working directory. All the path will be relative to WORKDIR
WORKDIR /usr/src/app

# Copy over required files
COPY package*.json ./
COPY lerna.json .
COPY packages/${SERVICE} ./packages/${SERVICE}
COPY packages/proto ./packages/proto

# Install packages
RUN npm i
RUN npm run bootstrap

# Dev mode
CMD [ "npm" , "--prefix", "packages/${SERVICE}", "run", "dev" ]
