FROM node:13

# Setting working directory. All the path will be relative to WORKDIR
WORKDIR /usr/src/app

RUN npm i lerna -g --loglevel notice

# Installing dependencies
COPY package*.json ./
RUN npm install

# Copy root package.json
COPY package.json .
RUN npm install --loglevel notice

# Now copy relevant packages
COPY packages/backend ./packages/backend

COPY lerna.json .
RUN lerna bootstrap

# Dev mode
CMD [ "npm" , "--prefix", "packages/backend", "start" ]