version: '3'
services:
  redis-testing:
    image: redis:5.0.7-alpine # Use stable version
    container_name: redis-testing
    entrypoint: redis-server --appendonly yes # Start with data persistance

  backend-testing:
    container_name: backend-testing
    depends_on:
      - redis-testing
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        SERVICE: backend
    environment:
      SERVICE: backend
    volumes:
      - ./:/usr/src/app
      - ../proto:/usr/src/proto
      - /usr/src/app/node_modules
